all:
  hosts:
    node1:
      ansible_host: 10.0.0.231
      ip: 10.0.0.231
      access_ip: 10.0.0.231
    node2:
      ansible_host: 10.0.0.233
      ip: 10.0.0.233
      access_ip: 10.0.0.233
    node3:
      ansible_host: 10.0.0.246
      ip: 10.0.0.246
      access_ip: 10.0.0.246
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}